spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: admin

app:
  secret-key: tmNDKSlBzap3CxsSg0yYffBHF0t8CgnwxZiqI+WBUBPc0kineRBj8jFLI08hNCCj0MmnZq7hIhZaUCjd5Zr0QkjkMKooiOIOIOIKLK

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  liquibase:
    change-log: classpath:db.changelog/master.yaml
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    user: admin
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate